#!/usr/bin/env bash

pebildir="`pwd`/`dirname $BASH_SOURCE`"
export PEBIL_ROOT=$pebildir
echo "***** initializing environment using PEBIL_ROOT=$PEBIL_ROOT"
export LD_LIBRARY_PATH=${PEBIL_ROOT}/lib:${LD_LIBRARY_PATH}
export PATH=${PEBIL_ROOT}/bin:${PEBIL_ROOT}/scripts:${PATH}

