#ifndef _CacheStructures_h_
#define _CacheStructures_h_

/* Note : */
/*        this file is generated by ../scripts/generateCaches.pl script */
/*        using source as CacheDescriptions.txt */

#define __STRIDE_TARGET_SYSTEM 0

#define __SYSTEM_COUNT 53
uint8_t systemCount =  __SYSTEM_COUNT;
MemoryHierarchy systems[__SYSTEM_COUNT] = {
	{      /* <------ STRIDE SYSTEM */
	    0, /* sysid0 */
	    1, /* cache level count */
	    {
	    { {   8192,   1,   8, repl_dir }, {0, 0}, 0, NULL, NULL }  /* level 1 cache */
	    }
	},
	{
	    1, /* sysid1 */
	    3, /* cache level count */
	    {
	    { {    128,   2,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   1536,   4,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {   4096,   8,   9, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	    2, /* sysid2 */
	    3, /* cache level count */
	    {
	    { {    128,   2,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    768,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {   4096,   8,   9, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	    3, /* sysid3 */
	    2, /* cache level count */
	    {
	    { {    512,   2,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   1024,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	    4, /* sysid4 */
	    2, /* cache level count */
	    {
	    { {    256,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   4096,  12,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   14, /* sysid14 */
	    2, /* cache level count */
	    {
	    { {     32,   8,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   2048,   8,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   22, /* sysid22 */
	    3, /* cache level count */
	    {
	    { {     64,   4,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    768,  10,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {   6144,  12,   8, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	   23, /* sysid23 */
	    2, /* cache level count */
	    {
	    { {     64,   8,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   2048,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   26, /* sysid26 */
	    2, /* cache level count */
	    {
	    { {    256,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   8192,   4,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   27, /* sysid27 */
	    2, /* cache level count */
	    {
	    { {    256,   2,   5, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {  32768,   2,   5, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   29, /* sysid29 */
	    2, /* cache level count */
	    {
	    { {    256,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   4778,  12,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   30, /* sysid30 */
	    2, /* cache level count */
	    {
	    { {    256,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   6144,  12,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   31, /* sysid31 */
	    3, /* cache level count */
	    {
	    { {    128,   2,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    976,   4,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {   2136,   8,   9, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	   32, /* sysid32 */
	    3, /* cache level count */
	    {
	    { {    128,   2,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    358,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {   2136,   8,   9, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	   33, /* sysid33 */
	    2, /* cache level count */
	    {
	    { {    200,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   3498,  12,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   34, /* sysid34 */
	    2, /* cache level count */
	    {
	    { {     64,   8,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   1560,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   35, /* sysid35 */
	    3, /* cache level count */
	    {
	    { {     64,   4,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    358,  10,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {   3413,  12,   8, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	   36, /* sysid36 */
	    2, /* cache level count */
	    {
	    { {    200,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   5546,  12,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   37, /* sysid37 */
	    2, /* cache level count */
	    {
	    { {    476,   8,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   2048,   8,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   38, /* sysid38 */
	    2, /* cache level count */
	    {
	    { {    512,   2,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    512,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   39, /* sysid39 */
	    2, /* cache level count */
	    {
	    { {    512,   2,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   2048,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   40, /* sysid40 */
	    2, /* cache level count */
	    {
	    { {    512,   2,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   4096,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   41, /* sysid41 */
	    3, /* cache level count */
	    {
	    { {    256,   2,   5, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   4096,   4,   5, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {   4096,  16,   5, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	   42, /* sysid42 */
	    2, /* cache level count */
	    {
	    { {    200,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   6398,   4,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   43, /* sysid43 */
	    2, /* cache level count */
	    {
	    { {    512,   2,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    960,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   44, /* sysid44 */
	    3, /* cache level count */
	    {
	    { {     64,   4,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   1536,  10,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {  12288,  12,   8, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	   45, /* sysid45 */
	    3, /* cache level count */
	    {
	    { {     64,   4,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   1120,  10,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {  12288,  12,   8, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	   46, /* sysid46 */
	    2, /* cache level count */
	    {
	    { {     64,   8,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   2048,  24,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   47, /* sysid47 */
	    2, /* cache level count */
	    {
	    { {     64,   8,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    816,  24,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   48, /* sysid48 */
	    2, /* cache level count */
	    {
	    { {     64,   8,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    960,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   49, /* sysid49 */
	    2, /* cache level count */
	    {
	    { {     64,   8,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    552,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   50, /* sysid50 */
	    2, /* cache level count */
	    {
	    { {     64,   8,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   1224,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   51, /* sysid51 */
	    2, /* cache level count */
	    {
	    { {    256,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {  12288,   4,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   52, /* sysid52 */
	    2, /* cache level count */
	    {
	    { {    200,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {  10752,   4,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   53, /* sysid53 */
	    2, /* cache level count */
	    {
	    { {    512,   2,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    792,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   54, /* sysid54 */
	    2, /* cache level count */
	    {
	    { {     16,  64,   5, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   2048,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   55, /* sysid55 */
	    2, /* cache level count */
	    {
	    { {     16,  64,   5, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   2050,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   56, /* sysid56 */
	    2, /* cache level count */
	    {
	    { {    256,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {  18432,   4,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   57, /* sysid57 */
	    2, /* cache level count */
	    {
	    { {    200,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {  14400,   4,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   58, /* sysid58 */
	    3, /* cache level count */
	    {
	    { {     32,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   4096,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {   8192,  16,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	   60, /* sysid60 */
	    3, /* cache level count */
	    {
	    { {     32,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   2050,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {   7440,  16,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	   61, /* sysid61 */
	    3, /* cache level count */
	    {
	    { {     32,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   3552,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {   7440,  16,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	   62, /* sysid62 */
	    2, /* cache level count */
	    {
	    { {    256,   4,   5, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   2048,   2,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   63, /* sysid63 */
	    2, /* cache level count */
	    {
	    { {    256,   4,   5, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   1024,   2,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	   64, /* sysid64 */
	    3, /* cache level count */
	    {
	    { {    512,   2,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    512,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {    256,  32,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	   65, /* sysid65 */
	    3, /* cache level count */
	    {
	    { {    512,   2,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    512,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {    250,  32,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	   66, /* sysid66 */
	    3, /* cache level count */
	    {
	    { {    512,   2,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    512,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {    230,  32,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	   67, /* sysid67 */
	    1, /* cache level count */
	    {
	    { {      1, 8192,   3, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 1 cache */
	    }
	},
	{
	   68, /* sysid68 */
	    1, /* cache level count */
	    {
	    { {      1,   1,   5, repl_dir }, {0, 0}, 0, NULL, NULL }  /* level 1 cache */
	    }
	},
	{
	   69, /* sysid69 */
	    1, /* cache level count */
	    {
	    { {      1,   1,   6, repl_dir }, {0, 0}, 0, NULL, NULL }  /* level 1 cache */
	    }
	},
	{
	   70, /* sysid70 */
	    1, /* cache level count */
	    {
	    { {      1,   1,   7, repl_dir }, {0, 0}, 0, NULL, NULL }  /* level 1 cache */
	    }
	},
	{
	   71, /* sysid71 */
	    1, /* cache level count */
	    {
	    { {      1,   1,   8, repl_dir }, {0, 0}, 0, NULL, NULL }  /* level 1 cache */
	    }
	},
	{
	   72, /* sysid72 */
	    3, /* cache level count */
	    {
	    { {    512,   2,   6, repl_lru_vc }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    512,  16,   6, repl_lru_vc }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {    256,  32,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	}
};

#endif
