#ifndef _CacheStructures_h_
#define _CacheStructures_h_

/* Note : */
/*        this file is generated by ../scripts/generateCaches.pl script */
/*        using source as CacheDescriptions.txt */

#define __STRIDE_TARGET_SYSTEM 0

#define __SYSTEM_COUNT 5
uint8_t systemCount =  __SYSTEM_COUNT;
MemoryHierarchy systems[__SYSTEM_COUNT] = {
	{      /* <------ STRIDE SYSTEM */
	    0, /* sysid0 */
	    1, /* cache level count */
	    {
	    { {   8192,   1,   8, repl_dir }, {0, 0}, 0, NULL, NULL }  /* level 1 cache */
	    }
	},
	{
	    1, /* sysid1 */
	    3, /* cache level count */
	    {
	    { {    128,   2,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   1536,   4,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {   4096,   8,   9, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	    2, /* sysid2 */
	    3, /* cache level count */
	    {
	    { {    128,   2,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {    768,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 2 cache */
	    { {   4096,   8,   9, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 3 cache */
	    }
	},
	{
	    3, /* sysid3 */
	    2, /* cache level count */
	    {
	    { {    512,   2,   6, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   1024,  16,   6, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	},
	{
	    4, /* sysid4 */
	    2, /* cache level count */
	    {
	    { {    256,   8,   7, repl_lru }, {0, 0}, 0, NULL, NULL }, /* level 1 cache */
	    { {   4096,  12,   7, repl_lru }, {0, 0}, 0, NULL, NULL }  /* level 2 cache */
	    }
	}
};

#endif
